# Generated by Django 3.2.6 on 2022-04-20 02:23

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(default='default markdown text'),
            preserve_default=False,
        ),
    ]
