# Generated by Django 3.2.6 on 2022-03-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220225_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(help_text='First 200 Chars of article for Blog Index Page.', max_length=200),
        ),
    ]
